In [1]:
!pip install pydantic==1.10.2
!pip install underthesea
!pip install emoji
!pip install demoji
!pip install pyvi
!pip install import-ipynb

In [2]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [3]:
import pandas as pd
import numpy as np
from underthesea import word_tokenize, pos_tag, sent_tokenize
import regex
import demoji
from pyvi import ViPosTagger, ViTokenizer
import string
import re
import datetime

In [4]:
import pandas as pd
from nltk.tokenize import word_tokenize
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import ExtraTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from imblearn.over_sampling import SMOTE

In [5]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive


In [6]:
%cd '/content/gdrive/MyDrive/Colab/LDS0_K294_T2C7/PROJECT3/'

/content/gdrive/MyDrive/Colab/LDS0_K294_T2C7/PROJECT3


In [7]:
#from Library_Functions import*

In [8]:
import pandas as pd
data = pd.read_csv("data/pre_data.csv", delimiter=',',index_col=0)
data.head()

Comment  Rating    class  \
0                                    Đã thư rất ngon     5.0  Neutral   
1  Tệ mua mang về cho 1 gói tương ớt Và xin thêm ...     1.0  Dislike   
2  21h30 2 đứa nhỏ kêu đói sau 1 hồi bình loạn là...     4.2  Dislike   
3  Nay có khuyến mại mua 1 tặng 1 trà kem sữa Uốn...     7.4     Like   
4  Thề lâu lắm rồi t mới tức giận ntn T có xem qu...     1.0  Dislike   

                                         Comment_pre  
0                                                thư  
1  tệ gói tương_ớt tương_về tương món gói không_h...  
2  kêu đói hồi bình_loạn chốt háo_hức nỡ_lòng lượ...  
3                 khuyến_mại tặng trà sữa uống đồ_ăn  
4  thề lắm tức_giận thế_này quảng_cáo minion háo_...

In [9]:
data.isna().sum()

Comment        0
Rating         0
class          0
Comment_pre    0
dtype: int64

In [10]:
data.count()

Comment        26579
Rating         26579
class          26579
Comment_pre    26579
dtype: int64

In [11]:
def my_tokenizer(text):
    return word_tokenize(text)

In [12]:
!pip install lazypredict

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from lazypredict.Supervised import LazyClassifier

In [14]:
text_data=data["Comment_pre"]
target=data["class"]

In [15]:
target = target.replace("Like", 0)
target = target.replace("Dislike", 1)
target = target.replace("Neutral", 2)

In [16]:
count = CountVectorizer(max_features=1000)
count.fit(text_data)
bag_of_words = count.transform(text_data)
bag_of_words

<26579x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 353073 stored elements in Compressed Sparse Row format>

In [17]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [18]:
y = np.array(target)
y

array([2, 1, 1, ..., 1, 0, 0])

In [19]:
data["class"].head(200).values

array(['Neutral', 'Dislike', 'Dislike', 'Like', 'Dislike', 'Like',
       'Dislike', 'Neutral', 'Dislike', 'Dislike', 'Dislike', 'Like',
       'Dislike', 'Neutral', 'Dislike', 'Dislike', 'Like', 'Dislike',
       'Dislike', 'Dislike', 'Neutral', 'Like', 'Like', 'Like', 'Like',
       'Like', 'Dislike', 'Neutral', 'Like', 'Dislike', 'Like', 'Neutral',
       'Like', 'Like', 'Dislike', 'Like', 'Like', 'Dislike', 'Like',
       'Like', 'Like', 'Like', 'Like', 'Like', 'Dislike', 'Like',
       'Neutral', 'Like', 'Neutral', 'Dislike', 'Like', 'Like', 'Like',
       'Neutral', 'Like', 'Like', 'Like', 'Like', 'Neutral', 'Like',
       'Like', 'Like', 'Like', 'Neutral', 'Like', 'Like', 'Like', 'Like',
       'Dislike', 'Like', 'Like', 'Like', 'Dislike', 'Neutral', 'Neutral',
       'Like', 'Dislike', 'Like', 'Like', 'Like', 'Neutral', 'Dislike',
       'Dislike', 'Dislike', 'Dislike', 'Like', 'Like', 'Like', 'Like',
       'Like', 'Like', 'Dislike', 'Like', 'Like', 'Like', 'Like',
       'Neu

In [20]:
y[:200]

array([2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0,
       0, 0, 0, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 2, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 2, 0,
       0, 1, 2, 1, 0, 1, 1, 2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 2,
       0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1,
       2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0])

### Sử dụng LazyClassifier để tìm ra các model tốt nhất

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [22]:
# clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
# models, predictions = clf.fit(X_train, X_test, y_train, y_test)

In [23]:
# Sử dụng colab free không chạy nổi

# Chọn các model ExtraTreeClassifier, BernoulliNB, LogisticRegression, DecisionTreeClassifier để chạy

### BernoulliNB

In [24]:
pipeline_bnl = Pipeline([
    ('tfidf', TfidfTransformer()),
    ('model', BernoulliNB())
])

pipeline_bnl.fit(X_train, y_train)

y_pred_bnl = pipeline_bnl.predict(X_test)

accuracy_bnl = accuracy_score(y_test, y_pred_bnl)
print("Accuracy: ", accuracy_bnl)
print("-"*60)
print(confusion_matrix(y_test, y_pred_bnl))
print("-"*60)
print(classification_report(y_test, y_pred_bnl))

Accuracy:  0.7430398796087284
------------------------------------------------------------
[[3089  269  210]
 [  76  624   89]
 [ 487  235  237]]
------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.85      0.87      0.86      3568
           1       0.55      0.79      0.65       789
           2       0.44      0.25      0.32       959

    accuracy                           0.74      5316
   macro avg       0.61      0.63      0.61      5316
weighted avg       0.73      0.74      0.73      5316



### LogisticRegression

In [25]:
pipeline_lr = Pipeline([
    ('tfidf', TfidfTransformer()),
    ('model', LogisticRegression())
])

pipeline_lr.fit(X_train, y_train)

y_pred_lr = pipeline_lr.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)
print("-"*60)
print(confusion_matrix(y_test, y_pred_lr))
print("-"*60)
print(classification_report(y_test, y_pred_lr))

Accuracy: 0.7765237020316027
------------------------------------------------------------
[[3426   43   99]
 [ 188  521   80]
 [ 645  133  181]]
------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.80      0.96      0.88      3568
           1       0.75      0.66      0.70       789
           2       0.50      0.19      0.27       959

    accuracy                           0.78      5316
   macro avg       0.68      0.60      0.62      5316
weighted avg       0.74      0.78      0.74      5316



### DecisionTree

In [26]:
pipeline_dct = Pipeline([
    ('tfidf', TfidfTransformer()),
    ('model', DecisionTreeClassifier())
])

pipeline_dct.fit(X_train, y_train)

y_pred_dct = pipeline_dct.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_dct)
print("Accuracy:", accuracy)
print("-"*60)
print(confusion_matrix(y_test, y_pred_dct))
print("-"*60)
print(classification_report(y_test, y_pred_dct))

Accuracy: 0.6657261098570354
------------------------------------------------------------
[[2841  190  537]
 [ 195  445  149]
 [ 542  164  253]]
------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.79      0.80      0.80      3568
           1       0.56      0.56      0.56       789
           2       0.27      0.26      0.27       959

    accuracy                           0.67      5316
   macro avg       0.54      0.54      0.54      5316
weighted avg       0.66      0.67      0.66      5316



### ExtraTreeClassifier

In [27]:
pipeline_etc = Pipeline([
    ('tfidf', TfidfTransformer()),
    ('model', ExtraTreeClassifier())
])

pipeline_etc.fit(X_train, y_train)

y_pred_etc = pipeline_etc.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_etc)
print("Accuracy: ", accuracy_knn)
print("-"*60)
print(confusion_matrix(y_test, y_pred_etc))
print("-"*60)
print(classification_report(y_test, y_pred_etc))

Accuracy:  0.6369450714823175
------------------------------------------------------------
[[2757  263  548]
 [ 237  378  174]
 [ 569  139  251]]
------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.77      0.77      0.77      3568
           1       0.48      0.48      0.48       789
           2       0.26      0.26      0.26       959

    accuracy                           0.64      5316
   macro avg       0.51      0.50      0.50      5316
weighted avg       0.64      0.64      0.64      5316



### Nhận xét:
- Sau khi chạy model cho ra accuracy chưa ổn từ 65-78%, xem xét lại recall và f1-score, nhận thấy rằng các model chưa thực sự hiệu quả và cần cải thiện.
- Chỉ có model LogisticRegression thì ổn được chút
- Có thể Resample Data để cân bằng lại dữ liệu và xem tính hiệu