In [1]:
!pip install pydantic==1.10.2
!pip install underthesea
!pip install emoji
!pip install demoji
!pip install pyvi
!pip install import-ipynb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 52.9 MB/s eta 0:00:00
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.7.2
    Uninstalling pydantic-2.7.2:
      Successfully uninstalled pydantic-2.7.2
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 59.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 58.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 657.8/657.8 kB 45.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.4/431.4 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 kB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 56.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.2 MB/s eta 0:00:00


In [2]:
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [3]:
import pandas as pd
import numpy as np
from underthesea import word_tokenize, pos_tag, sent_tokenize
import regex
import demoji
from pyvi import ViPosTagger, ViTokenizer
import string
import re
import datetime

In [14]:
import pandas as pd
from nltk.tokenize import word_tokenize
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import ExtraTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import RandomOverSampler

In [5]:
from google.colab import drive
drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive


In [6]:
%cd '/content/gdrive/MyDrive/Colab/LDS0_K294_T2C7/PROJECT3/'

/content/gdrive/MyDrive/Colab/LDS0_K294_T2C7/PROJECT3


In [7]:
#from Library_Functions import*

In [8]:
import pandas as pd
data = pd.read_csv("data/pre_data.csv", delimiter=',',index_col=0)
data.head()

Comment  Rating    class  \
0                                    Đã thư rất ngon     5.0  Neutral   
1  Tệ mua mang về cho 1 gói tương ớt Và xin thêm ...     1.0  Dislike   
2  21h30 2 đứa nhỏ kêu đói sau 1 hồi bình loạn là...     4.2  Dislike   
3  Nay có khuyến mại mua 1 tặng 1 trà kem sữa Uốn...     7.4     Like   
4  Thề lâu lắm rồi t mới tức giận ntn T có xem qu...     1.0  Dislike   

                                         Comment_pre  
0                                                thư  
1  tệ gói tương_ớt tương_về tương món gói không_h...  
2  kêu đói hồi bình_loạn chốt háo_hức nỡ_lòng lượ...  
3                 khuyến_mại tặng trà sữa uống đồ_ăn  
4  thề lắm tức_giận thế_này quảng_cáo minion háo_...

In [9]:
data.isna().sum()

Comment        0
Rating         0
class          0
Comment_pre    0
dtype: int64

In [10]:
data.count()

Comment        26579
Rating         26579
class          26579
Comment_pre    26579
dtype: int64

In [11]:
X=data["Comment_pre"]
y=data["class"]

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [15]:
ros = RandomOverSampler()
X_train_resampled, y_train_resampled = ros.fit_resample(np.array(X_train).reshape(-1, 1), np.array(y_train).reshape(-1, 1));
train_df_reampled = pd.DataFrame(list(zip([x[0] for x in X_train_resampled], y_train_resampled)), columns = ['Comment_pre', 'class']);

In [16]:
train_df_reampled["class"].value_counts()

class
Dislike    14000
Like       14000
Neutral    14000
Name: count, dtype: int64

In [17]:
train_df_reampled.to_csv("data/data_resample_1.csv")

In [18]:
X_train_resampled, X_test, y_train_resampled, y_test = train_test_split(train_df_reampled["Comment_pre"],train_df_reampled["class"], test_size=0.2,random_state=42)

In [19]:
train_df_reampled.loc[train_df_reampled["Comment_pre"]==""]

Empty DataFrame
Columns: [Comment_pre, class]
Index: []

In [20]:
X_train_resampled=train_df_reampled["Comment_pre"]
y_train_resampled=train_df_reampled["class"]

In [21]:
def my_tokenizer(text):
    return word_tokenize(text)

### BernoulliNB

In [22]:
pipeline_bnl = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('model', BernoulliNB())
])

pipeline_bnl.fit(X_train_resampled, y_train_resampled)

y_pred_bnl = pipeline_bnl.predict(X_test)

accuracy_bnl = accuracy_score(y_test, y_pred_bnl)
print("Accuracy: ", accuracy_bnl)
print("-"*60)
print(confusion_matrix(y_test, y_pred_bnl))
print("-"*60)
print(classification_report(y_test, y_pred_bnl))

Accuracy:  0.8605952380952381
------------------------------------------------------------
[[2631   27   79]
 [ 187 2425  250]
 [ 324  304 2173]]
------------------------------------------------------------
              precision    recall  f1-score   support

     Dislike       0.84      0.96      0.90      2737
        Like       0.88      0.85      0.86      2862
     Neutral       0.87      0.78      0.82      2801

    accuracy                           0.86      8400
   macro avg       0.86      0.86      0.86      8400
weighted avg       0.86      0.86      0.86      8400



### LogisticRegression

In [23]:
pipeline_lr = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('model', LogisticRegression())
])

pipeline_lr.fit(X_train_resampled, y_train_resampled)

y_pred_lr = pipeline_lr.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy_lr)
print("-"*60)
print(confusion_matrix(y_test, y_pred_lr))
print("-"*60)
print(classification_report(y_test, y_pred_lr))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.9030952380952381
------------------------------------------------------------
[[2675   18   44]
 [  53 2525  284]
 [ 132  283 2386]]
------------------------------------------------------------
              precision    recall  f1-score   support

     Dislike       0.94      0.98      0.96      2737
        Like       0.89      0.88      0.89      2862
     Neutral       0.88      0.85      0.87      2801

    accuracy                           0.90      8400
   macro avg       0.90      0.90      0.90      8400
weighted avg       0.90      0.90      0.90      8400



In [24]:
from joblib import dump
dump(pipeline_lr, 'model/Project_3_LogisticRegression_sklearn_3.joblib')

['model/Project_3_LogisticRegression_sklearn_3.joblib']

### DecisionTree

In [25]:
pipeline_dct = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('model', DecisionTreeClassifier())
])

pipeline_dct.fit(X_train_resampled, y_train_resampled)

y_pred_dct = pipeline_dct.predict(X_test)

accuracy_dct = accuracy_score(y_test, y_pred_dct)
print("Accuracy:", accuracy_dct)
print("-"*60)
print(confusion_matrix(y_test, y_pred_dct))
print("-"*60)
print(classification_report(y_test, y_pred_dct))

Accuracy: 0.9966666666666667
------------------------------------------------------------
[[2737    0    0]
 [   0 2841   21]
 [   0    7 2794]]
------------------------------------------------------------
              precision    recall  f1-score   support

     Dislike       1.00      1.00      1.00      2737
        Like       1.00      0.99      1.00      2862
     Neutral       0.99      1.00      1.00      2801

    accuracy                           1.00      8400
   macro avg       1.00      1.00      1.00      8400
weighted avg       1.00      1.00      1.00      8400



In [26]:
from joblib import dump
dump(pipeline_dct, 'model/Project_3_DecisionTree_sklearn_4.joblib')

['model/Project_3_DecisionTree_sklearn_4.joblib']

### ExtraTreeClassifier

In [27]:
pipeline_etc = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('model', ExtraTreeClassifier())
])

pipeline_etc.fit(X_train_resampled, y_train_resampled)

y_pred_etc = pipeline_etc.predict(X_test)

accuracy_etc = accuracy_score(y_test, y_pred_etc)
print("Accuracy: ", accuracy_etc)
print("-"*60)
print(confusion_matrix(y_test, y_pred_etc))
print("-"*60)
print(classification_report(y_test, y_pred_etc))

Accuracy:  0.9966666666666667
------------------------------------------------------------
[[2737    0    0]
 [   0 2841   21]
 [   0    7 2794]]
------------------------------------------------------------
              precision    recall  f1-score   support

     Dislike       1.00      1.00      1.00      2737
        Like       1.00      0.99      1.00      2862
     Neutral       0.99      1.00      1.00      2801

    accuracy                           1.00      8400
   macro avg       1.00      1.00      1.00      8400
weighted avg       1.00      1.00      1.00      8400



In [28]:
from joblib import dump
dump(pipeline_dct, 'model/Project_3_Extra_sklearn_4.joblib')

['model/Project_3_Extra_sklearn_4.joblib']

In [29]:
text=["dở_tệ không tiền mắc quá"]

In [30]:
text=pd.DataFrame({'Comment_pre':text})
import joblib
loaded_model = joblib.load("model/Project_3_DecisionTree_sklearn_4.joblib")
result = loaded_model.predict(text["Comment_pre"])
result

array(['Dislike'], dtype=object)

In [40]:
text1 = ["Món ăn rất ngon giá rẻ"]

In [41]:
text1=pd.DataFrame({'Comment_pre':text1})
import joblib
loaded_model = joblib.load("model/Project_3_DecisionTree_sklearn_4.joblib")
result = loaded_model.predict(text["Comment_pre"])
result

array(['Dislike'], dtype=object)